In [3]:
import numpy as np

In [4]:
# create an array
civilian_deaths = np.array([4352, 233, 3245, 256, 2394])
civilian_deaths

array([4352,  233, 3245,  256, 2394])

In [5]:
# mean of the array
civilian_deaths.mean()

2096.0

In [6]:
# total of the array
civilian_deaths.sum()

10480

In [7]:
# smallest of the array
civilian_deaths.min()

233

In [8]:
# largest of the array
civilian_deaths.max()

4352

#Generating random numbers with Numpy

In [5]:
# generate a random number from the normal distribution
print np.random.normal()

# generate 4 random numbers from the normal distribution
print np.random.normal(size=4)

# generate 4 random numbers from the uniform distribution
print np.random.uniform(size=4)

# genrate 4 random integers between 1 and 100
print np.random.randint(1, 100, 4)

0.361664535411
[-1.29852657 -2.26093327 -0.33406977 -1.42121441]
[ 0.80959376  0.69632398  0.25595408  0.66276555]
[52 58 73 58]
